import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";

export default function Ben() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CS49 Personal Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/compsci 49 (1) 1.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div
          style={{
            marginLeft: "120px",
            marginTop: "10px",
            fontFamily: "Helvetica",
            fontWeight: 550,
            fontSize: "20px",
          }}
        >
          Test
        </div>
      </main>
    </div>
  );
}
