import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";

export default function Ben() {
  const html = `
  <html>
  <head>
    <title>My Next.js Page</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          <li>
            <a href="#">Home</a>
          </li>
          <li>
            <a href="#">About</a>
          </li>
          <li>
            <a href="#">Contact</a>
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <h1>Hello, World!</h1>
      <p>This is a sample Next.js page.</p>
    </main>
  </body>
</html>`;
  return (
    <div className={styles.container}>
      <Head>
        <title>CS49 Personal Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/compsci 49 (1) 1.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        {/* pure html calling below */}
        <div dangerouslySetInnerHTML={{ __html: html }} />
        <div
          style={{
            marginLeft: "120px",
            marginTop: "10px",
            fontFamily: "Helvetica",
            fontWeight: 550,
            fontSize: "20px",
          }}
        >
          Test
        </div>
      </main>
    </div>
  );
}
