import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";

export default function Conrad() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CS49 Personal Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/compsci 49 (1) 1.ico" />
      </Head>
      <Body>
        <h1>Hi all,</h1>
        <p>This is a personal page for Conrad Poon.
        </p>
        <img src="ripobama.jpg"></img>
      </Body>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>Conrad&apos;s Page : &#41;</h1>
      </main>
    </div>
  );
}
