import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";

export default function Emily() {
  return (
    <div className={styles.container}>
      <Head>
      <title>CS49 Personal Page</title>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/compsci 49 (1) 1.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
      <div>
      <h1 className={styles.title}>Hi Dardar!</h1>
      <h2 className={styles.title}>this is my cat Darcy, named after Mr. Darcy from Pride & Prejudice</h2>
          <img
          src = "darcy.jpg"
          alt="cat"
          width="70%"
          height="200%"
          style = {{
            position: "absolute",
            right: "200px",
          }}
        />
    </div>
      <h1 className={styles.title}>Emilyy&apos;s Page : &#41;</h1>
      </main>
    </div>
  );
  }
 