import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";
import React, { useState, useEffect } from "react";

export default function Jack() {
    const [colorIndex, setColorIndex] = useState(0);
    const colors = ["red", "orange", "yellow", "green", "blue", "indigo", "violet"];

    useEffect(() => {
        const intervalId = setInterval(() => {
            setColorIndex((colorIndex + 1) % colors.length);
        }, 5);
        return () => clearInterval(intervalId);
    }, [colorIndex]);

    return (
        <div className={styles.container} style={{ backgroundColor: colors[colorIndex] }}>
            <Head>
                <title>CS49 Personal Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/compsci 49 (1) 1.ico" />
            </Head>
            <Navbar />
            <main className={styles.main}>
                <div
                    style={{
                        fontFamily: "Comic Sans",
                        fontWeight: 550,
                        fontSize: "20px",
                    }}
                >
                    I'm Jack and I really hope you don't have epilepsy
                </div>
            </main>
        </div>
    );
}

// Written using a trained version of ChatGPT
