import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";

export default function Yoyo() {
  const html = `
  <html>
    <main>
          <form action="input.html" method = "GET">
              <label>Tell me Your Wish -></label>
              <input>
              <button>Toss a Coin In The Well</button>
        </form>
    </main>
  </body>
</html>`;

  return (
    <div className={styles.container}>
      <Head>
        <title>It's a Beautiful World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/compsci 49 (1) 1.ico" />

      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>yOYo&apos;s Page : &#41;</h1>
        <img src={"/yoyo.jpg"} width="400" height="400" boarder-radius="10" />

        <p className={styles.red} >@yOYo</p>
        
        {/* This to run the earlier work*/}
        <div dangerouslySetInnerHTML={{ __html: html }} /> 
      </main>
    </div>
  );
}
